### ISSUE TITLE
Title: Request for Clarification: Inconsistencies in Vectara Library Usage Documentation

### ISSUE THREAD

**Issue by MN-NR** [forrestbao/Vektara#8]
While trying to initialize the Vectara client as instructed, I faced issues. The provided initialization method using only three variables which didn't work. However, adding the vectara_api_key parameter along with customer_id, client_id, and client_secret led to successful initialization. This crucial detail is missing in the PyPI docs and demo usage. Updating the documentation would greatly help the Vectara community.

**Comment by forrestbao** [comment]
We apologize for the confusion. We are fixing it. When you use API keys, you shouldn't be needing client_id and client_secret anymore.  It should be done in a few hours.

**Comment by forrestbao** [comment]
Hi @MN-Noor I apologize for the inconvenience, the code and doc have been updated. Now you can use either Personal API key or OAuth2 credentials to authenticate. But API KEY is the first class citizen. Let us know if you run into other issues.

**Comment by MN-NR** [comment]
Thanks! Yeah, it works with an API key without needing client ID and client secrets.
